spring:
# 配置Mysql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.57.108:3306/shiro?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
# 端口
server:
  port: 80
# 配置Mybatis
mybatis:
  type-aliases-package: com.qingchen.shiro.studyshiro.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true